-- Demo rooms near Seoul Station (generated by tools/generate-seed.mjs).
INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)
  VALUES ('wydm9k95', 8, 37.554616928100586, 126.97053909301758, '서울역 앞', 0, 1781421941558, 1781421941558);
INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)
  VALUES ('wydm9kfm', 8, 37.55633354187012, 126.97225570678711, '서소문', 13, 1781421941558, 1781421641558);
INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)
  VALUES ('wydm9msg', 8, 37.560110092163086, 126.97568893432617, '시청 광장', 26, 1781421941558, 1781421341558);
INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)
  VALUES ('wydm9hpe', 8, 37.551870346069336, 126.96847915649414, '남대문로', 39, 1781421941558, 1781421041558);
INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)
  VALUES ('wydm9k7s', 8, 37.553415298461914, 126.97397232055664, NULL, 52, 1781421941558, 1781420741558);
