// One-off: generate worker/seed.sql with demo rooms near Seoul Station.
// Reimplements geohash encode/bounds (mirror of shared/geo/geohash.ts) so this
// script stays dependency-free.
import { writeFileSync } from "node:fs";

const BASE32 = "0123456789bcdefghjkmnpqrstuvwxyz";

function encode(lat, lng, precision) {
  let idx = 0, bit = 0, even = true, hash = "";
  let latMin = -90, latMax = 90, lngMin = -180, lngMax = 180;
  while (hash.length < precision) {
    if (even) {
      const mid = (lngMin + lngMax) / 2;
      if (lng >= mid) { idx = idx * 2 + 1; lngMin = mid; } else { idx = idx * 2; lngMax = mid; }
    } else {
      const mid = (latMin + latMax) / 2;
      if (lat >= mid) { idx = idx * 2 + 1; latMin = mid; } else { idx = idx * 2; latMax = mid; }
    }
    even = !even;
    if (++bit === 5) { hash += BASE32[idx]; bit = 0; idx = 0; }
  }
  return hash;
}

function bounds(hash) {
  let even = true, latMin = -90, latMax = 90, lngMin = -180, lngMax = 180;
  for (const ch of hash) {
    const cd = BASE32.indexOf(ch);
    for (let n = 4; n >= 0; n--) {
      const b = (cd >> n) & 1;
      if (even) { const mid = (lngMin + lngMax) / 2; if (b) lngMin = mid; else lngMax = mid; }
      else { const mid = (latMin + latMax) / 2; if (b) latMin = mid; else latMax = mid; }
      even = !even;
    }
  }
  return { lat: (latMin + latMax) / 2, lng: (lngMin + lngMax) / 2 };
}

const seeds = [
  { lat: 37.5547, lng: 126.9706, name: "서울역 앞" },
  { lat: 37.5563, lng: 126.9723, name: "서소문" },
  { lat: 37.5601, lng: 126.9756, name: "시청 광장" },
  { lat: 37.5519, lng: 126.9684, name: "남대문로" },
  { lat: 37.5535, lng: 126.9740, name: null },
];

const now = Date.now();
const rows = seeds.map((s, i) => {
  const gh = encode(s.lat, s.lng, 8);
  const c = bounds(gh);
  const px = (i * 13) % 60;
  const name = s.name === null ? "NULL" : `'${s.name.replace(/'/g, "''")}'`;
  const drawn = now - i * 5 * 60 * 1000;
  return `INSERT OR REPLACE INTO rooms (geohash, precision, center_lat, center_lng, name, pixel_count, created_at, last_drawn_at)\n  VALUES ('${gh}', 8, ${c.lat}, ${c.lng}, ${name}, ${px}, ${now}, ${drawn});`;
});

const sql = `-- Demo rooms near Seoul Station (generated by tools/generate-seed.mjs).\n${rows.join("\n")}\n`;
writeFileSync(new URL("../worker/seed.sql", import.meta.url), sql);
console.log(sql);
